# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0012_auto_20161022_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.URLField(verbose_name='\u5934\u50cf'),
        ),
    ]
