# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0013_auto_20161022_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='wechat',
        ),
        migrations.AddField(
            model_name='member',
            name='wechat_alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5fae\u4fe1\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='member',
            name='wechat_nick',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5fae\u4fe1\u6635\u79f0'),
        ),
        migrations.AddField(
            model_name='member',
            name='wechat_remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5fae\u4fe1\u5907\u6ce8'),
        ),
    ]
