# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('slug', models.SlugField(blank=True, default='', null=True, verbose_name='Slug')),
                ('cover', models.ImageField(blank=True, max_length=200, upload_to='category', verbose_name='\u5206\u7c7b\u56fe\u7247')),
                ('ordering', models.PositiveIntegerField(default=999, editable=False, verbose_name='\u6392\u5e8f')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u6fc0\u6d3b')),
                ('keyword', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5206\u7c7b\u5173\u952e\u5b57')),
                ('channel', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u9891\u9053')),
                ('catids', models.BigIntegerField(blank=True, null=True, verbose_name='\u6dd8\u5b9d\u5206\u7c7b')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5546\u54c1\u6570')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kernel.Category')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u7c7b\u522b',
                'verbose_name_plural': '\u5546\u54c1\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u540d\u79f0')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u4ef7\u683c')),
                ('units', models.CharField(max_length=50, verbose_name='\u5355\u4f4d')),
                ('order', models.IntegerField(default='1', verbose_name='\u6392\u5e8f')),
                ('cover', imagekit.models.fields.ProcessedImageField(help_text='\u56fe\u7247\u5c3a\u5bf8\u6700\u597d\u4e3a720x240', null=True, upload_to='goods', verbose_name='\u56fe\u7247')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.Category')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u5217\u8868',
                'verbose_name_plural': '\u5546\u54c1\u5217\u8868',
            },
        ),
    ]
