# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0003_auto_20161029_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '\u5ba2\u6237\u5217\u8868', 'verbose_name_plural': '\u5ba2\u6237\u5217\u8868'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': '\u5ba2\u6237\u5206\u7ec4', 'verbose_name_plural': '\u5ba2\u6237\u5206\u7ec4'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': '\u8ba2\u5355\u5217\u8868', 'verbose_name_plural': '\u8ba2\u5355\u5217\u8868'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ordering',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='catids',
        ),
        migrations.RemoveField(
            model_name='category',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='category', verbose_name='\u5206\u7c7b\u56fe\u7247'),
        ),
    ]
