# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0005_auto_20161029_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='name',
            new_name='title',
        ),
    ]
