# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20161017_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=100, verbose_name='\u4ee3\u7801')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u540d\u79f0')),
                ('industry', models.CharField(default='', max_length=100, verbose_name='\u6240\u5c5e\u884c\u4e1a')),
                ('pe', models.CharField(default='', max_length=100, verbose_name='\u5e02\u76c8\u7387')),
                ('outstanding', models.CharField(default='', max_length=100, verbose_name='\u6d41\u901a\u80a1\u672c')),
                ('totals', models.CharField(default='', max_length=100, verbose_name='\u603b\u80a1\u672c(\u4e07)')),
                ('totalAssets', models.CharField(default='', max_length=100, verbose_name='\u603b\u8d44\u4ea7(\u4e07)')),
                ('liquidAssets', models.CharField(default='', max_length=100, verbose_name='\u6d41\u52a8\u8d44\u4ea7')),
                ('fixedAssets', models.CharField(default='', max_length=100, verbose_name='\u56fa\u5b9a\u8d44\u4ea7')),
                ('reserved', models.CharField(default='', max_length=100, verbose_name='\u516c\u79ef\u91d1')),
                ('reservedPerShare', models.CharField(default='', max_length=100, verbose_name='\u6bcf\u80a1\u516c\u79ef\u91d1')),
                ('eps', models.CharField(default='', max_length=100, verbose_name='\u6bcf\u80a1\u6536\u76ca')),
                ('bvps', models.CharField(default='', max_length=100, verbose_name='\u6bcf\u80a1\u51c0\u8d44')),
                ('pb', models.CharField(default='', max_length=100, verbose_name='\u5e02\u51c0\u7387')),
                ('timeToMarket', models.CharField(default='', max_length=100, verbose_name='\u4e0a\u5e02\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u80a1\u7968\u57fa\u672c\u9762',
                'verbose_name_plural': '\u80a1\u7968\u57fa\u672c\u9762',
            },
        ),
    ]
