# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0007_auto_20161105_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='price',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='client',
            name='order',
        ),
        migrations.RemoveField(
            model_name='client',
            name='units',
        ),
        migrations.AlterField(
            model_name='orders',
            name='units',
            field=models.CharField(choices=[('\u76d2', '\u76d2'), ('\u7bb1', '\u7bb1'), ('\u5957', '\u5957'), ('\u4e2a', '\u4e2a')], max_length=50, verbose_name='\u5355\u4f4d'),
        ),
    ]
