# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0008_auto_20161105_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='catids',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='parent',
        ),
    ]
