# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_basic_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=100, verbose_name='\u540d\u8bcd')),
                ('content', models.TextField(default='', verbose_name='\u89e3\u91ca')),
            ],
            options={
                'verbose_name': '\u540d\u8bcd\u89e3\u91ca',
                'verbose_name_plural': '\u540d\u8bcd\u89e3\u91ca',
            },
        ),
    ]
