# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0009_auto_20161105_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='level',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=64, verbose_name='\u5206\u7ec4\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u7528\u6237\u6570'),
        ),
    ]
