# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0013_auto_20161105_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.UUIDField(default=b'8552860fa34711e6bc8480e65000a9b4', editable=False, verbose_name='\u8ba2\u5355\u53f7'),
        ),
    ]
