# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0015_auto_20161105_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.CharField(default=b'f12ef897a34711e6ab4180e65000a9b4', editable=False, max_length=200, verbose_name='\u8ba2\u5355\u53f7'),
        ),
    ]
