# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 19:24
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0018_auto_20161105_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='category',
            new_name='cats',
        ),
        migrations.AddField(
            model_name='goods',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
