# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0020_orders_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='client',
        ),
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u8d2d\u7269\u603b\u8ba1'),
        ),
        migrations.AddField(
            model_name='orders',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='orders',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u5546\u54c1\u5355\u4ef7'),
        ),
        migrations.AddField(
            model_name='orders',
            name='uin',
            field=models.CharField(default='', max_length=100, verbose_name='\u5546\u54c1\u6570\u91cf'),
        ),
    ]
