# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0021_auto_20161106_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='token',
            field=models.CharField(default='', max_length=100, verbose_name='\u8ba2\u5355\u6807\u793a'),
        ),
    ]
