# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 13:38
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0022_orders_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='\u56fe\u7247\u5c3a\u5bf8\u6700\u597d\u4e3a720x240', null=True, upload_to='goods', verbose_name='\u56fe\u7247'),
        ),
    ]
