# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0025_orders_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='cats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kernel.Category'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='tags',
            field=models.CharField(help_text='\u591a\u4e2a\u5173\u952e\u5b57\u4e4b\u95f4\u9017\u53f7\u9694\u5f00', max_length=200, verbose_name='\u6807\u7b7e\u5173\u952e\u5b57'),
        ),
    ]
