# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0026_auto_20161112_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='nick',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5fae\u4fe1\u6635\u79f0'),
        ),
    ]
