# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0027_orders_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='\u987e\u5ba2\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='orders',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u987e\u5ba2\u7535\u8bdd'),
        ),
    ]
