# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0030_goods_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='cats',
        ),
        migrations.AlterField(
            model_name='orders',
            name='openid',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='openid'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Created', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='uin',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5fae\u4fe1\u6807\u793a'),
        ),
    ]
