# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0031_auto_20161112_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='express',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5feb\u9012\u5355\u53f7'),
        ),
    ]
